[package]
name = "matryoshka_tic_tac_toe"
version = "0.1.0"
authors = ["Kurtis Charnock <kurtis@charno.cc>"]
edition = "2018"

[[bin]]
name = "game"
path = "src/game/main.rs"

[[bin]]
name = "solver"
path = "src/solver/main.rs"

[dependencies]
rayon = "1.5.1"
smallvec = "1.6.1"
